sudo: false

branches:
  only:
    - publicGithubDevelop

script:
  - wget https://sourceforge.net/projects/doxygen/files/rel-1.9.2/doxygen-1.9.2.linux.bin.tar.gz/download
  - tar -zxvf download
  - ./doxygen-1.8.13/bin/doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: publicGithubDevelop
